repo_url: https://github.com/haysberg/random-veille
edit_uri: edit/main/docs/
site_name: My Docs
theme:
  language: fr
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - toc.follow
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
    lang: fr
  - optimize